---
- hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Determine the timestamp for the backup once for all nodes
      set_fact:
        now: '{{ lookup("pipe", "date +%F-%T") }}'

- hosts: automationcontroller:sso:automationhub[0]
  any_errors_fatal: true
  gather_facts: yes
  vars_files: vars/collection_global_vars.yml
  tasks:
    - include_role:
        name: check_config_static
      vars:
        now: "{{ hostvars['localhost']['now'] }}"

    - include_role:
        name: config_dynamic
      vars:
        now: "{{ hostvars['localhost']['now'] }}"

    - include_role:
        name: backup
      vars:
        now: "{{ hostvars['localhost']['now'] }}"
